### ISSUE TITLE
Soot Version

### ISSUE THREAD

**Issue by linghui2016** [rohanpadhye/vasco#9]
Hi, 

can you tell me which version of soot is used in VASCO? 

thanks and best regards,
Linghui

**Comment by rohanpadhye** [comment]
Hi Linghui,

I have not seen Soot using version numbers since [version 2.5.0, released back in 2012](https://github.com/Sable/soot/releases). 

You should be able to use the [nightly build](https://soot-build.cs.uni-paderborn.de/nightly/soot/), which I believe is synchronized with [their `develop` branch](https://github.com/Sable/soot/tree/develop) and contains the latest version. Ideally, VASCO should work with this version, assuming the API is backward-compatible.

Please open an issue if you find that you are having trouble using VASCO with some specific newer version of Soot.

**Comment by oparisy** [comment]
I have indeed been able to use `sootclasses-trunk.jar` from a recent nightly build without issue.

**Comment by linghui2016** [comment]
I used the nightly build from  02-Oct-2017 11:39   and got the following errors. I also tried an earlier version of nightly build and it only works for SignTest but not for CopyConstantTest.
![vasco](https://user-images.githubusercontent.com/18470909/31376033-ce33aea6-ada3-11e7-8038-657c1adcc34b.png)

**Comment by rohanpadhye** [comment]
@linghui2016: Thanks for the report. I'll look into it. Can you tell me for which class you got the `NoClassDefError`? There is a window blocking the class name in the screenshot that you attached.

**Comment by rohanpadhye** [comment]
Just tested with the latest nightly build of Soot (October 10, 2017) and it works fine for me. I used the fat JAR they provide that includes all dependencies.

I've updated the README to add instructions on downloading the nightly build. Let me know if you still have issues after following those steps.

**Comment by linghui2016** [comment]
Hi Rohan,

Thank you for testing it. I just tested the latest nightly build and it worked for SignTest. But for CopyConstantTest I still got exceptions as shown in the following screenshot.
![vasco](https://user-images.githubusercontent.com/18470909/31403777-755c9e26-adfa-11e7-8837-858865da2d45.png)

**Comment by rohanpadhye** [comment]
@linghui2016 : Since you've opened the issue, I've also moved the test cases (i.e. sample classes to be analyzed) from the `tests` package to the `vasco.tests` package so that they can all be built using Ant without polluting the global namespace. Just be aware of this when you pull the latest commit.

**Comment by linghui2016** [comment]
Hi Rohan, thanks for solving this issue. The problem is the java to jimple frontend in soot. 
soot.JastAddJ is the frontend(in stacktrace). This is outdated. Don't use soot to transform java to jimple but only bytecode to jimple. (I just have a soot expert in my office)

**Comment by rohanpadhye** [comment]
@linghui2016 Thanks for letting me know. I was not aware of this (I haven't been keeping track of Soot).
